### ISSUE TITLE
How can I get the min_ts and max_ts in dataset.py

### ISSUE THREAD

**Issue by unlimition** [Autumn945/MGNN-SPred#2]
I  had known N in dataset.py is the len(yc_part) in preprocessing_data.py  .
But I have not known how I can get the min_ts and max_ts in dataset.py 
`
     if ds == 'yc64' or ds == 'test':
            self.N = 144527
            self.reader = self.yc64
            self.min_ts, self.max_ts = 1411604904, 1412017199
        elif ds == 'yc4':
            self.N = 2312432
            self.reader = self.yc4
            self.min_ts, self.max_ts = 1408507486, 1412017199
        elif ds == 'yc':
            self.N = 9249729
            self.reader = self.yc
            self.min_ts, self.max_ts = 1396292400, 1412017199
` 
I think they are buys.dat's max_ts and min_ts but it's not correlative
`
    max, min, dt
    1396292731 1412015712
`
`
     self.min_ts, self.max_ts = 1396292400, 1412017199
`

I want to figure out it . I need some help

**Comment by Autumn945** [comment]
“ts” is an abbreviation for timestamp
1396292400：2014/4/1 3:0:0
1412017199：2014/9/30 2:59:59
all data is in this time range, but may not on the boundary
1396292400 <= data timestamp <= 1412017199

**Comment by Autumn945** [comment]
max, min, dt 1396292731 1412015712 is **2014/4/1 3:5:31 and 2014/9/30 2:35:12**
self.min_ts, self.max_ts = 1396292400, 1412017199 is **2014/4/1 3:0:0 and 2014/9/30 2:59:59**
I manually moved the timestamp to hour

**Comment by unlimition** [comment]
> 
> 
> max, min, dt 1396292731 1412015712 is **2014/4/1 3:5:31 and 2014/9/30 2:35:12**
> self.min_ts, self.max_ts = 1396292400, 1412017199 is **2014/4/1 3:0:0 and 2014/9/30 2:59:59**
> I manually moved the timestamp to hour

Thank your reply and help. I knew.
