### ISSUE TITLE
question about the data construction

### ISSUE THREAD

**Issue by jinweiluo** [Autumn945/MGNN-SPred#4]
Thanks for your great work and the share of code.
in the dataset.py  
line 119:
 if len(click_history) >= 5 and len(share_history) >= 1:
Could you please tell me that what this "5" means ?
The max_seq_len is set as 3 for yoochoose dataset according to the paper but this constraint of min_click_history haven't been noticed.

**Comment by Autumn945** [comment]
This can be regarded as a condition for filtering the data set.
We did not consider the user cold start situation, so the user is restricted to at least 5 click records and 1 sharing record in each data example.
This constraint will not be change, no matter the hyper-parametric "max_seq_len".
Different constraint will genarate different dataset, then the experimental results are not comparable.

I am sorry for that we forgot to mention this in the paper.

**Comment by jinweiluo** [comment]
oh yeah, I see. Thanks for your quick reply.
